// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz1SzMHVa_1jo3vQKm-mWIXqxrWsVeNzA',
    appId: '1:62306167229:web:48f0f40f099dbf09af8ad4',
    messagingSenderId: '62306167229',
    projectId: 'sima-pengiriman',
    authDomain: 'sima-pengiriman.firebaseapp.com',
    databaseURL: 'https://sima-pengiriman-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sima-pengiriman.appspot.com',
    measurementId: 'G-H4MJHLP8N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mmUzG8zAQ7Xgks83Q-T_NmoZyMMi4yI',
    appId: '1:62306167229:android:235a5163b90ce619af8ad4',
    messagingSenderId: '62306167229',
    projectId: 'sima-pengiriman',
    databaseURL: 'https://sima-pengiriman-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sima-pengiriman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpvgKyX6InpXHbYfxkBT-SXP0QMBVvVMk',
    appId: '1:62306167229:ios:82d22bae79cb016faf8ad4',
    messagingSenderId: '62306167229',
    projectId: 'sima-pengiriman',
    databaseURL: 'https://sima-pengiriman-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sima-pengiriman.appspot.com',
    iosBundleId: 'com.example.simaPengiriman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpvgKyX6InpXHbYfxkBT-SXP0QMBVvVMk',
    appId: '1:62306167229:ios:722b39d3dfaabc4caf8ad4',
    messagingSenderId: '62306167229',
    projectId: 'sima-pengiriman',
    databaseURL: 'https://sima-pengiriman-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sima-pengiriman.appspot.com',
    iosBundleId: 'com.example.simaPengiriman.RunnerTests',
  );
}
